### ISSUE TITLE
PDF generation failing on production

### ISSUE THREAD

**Issue by eoinkelly** [ODNZSL/nzsl-online#1149]
Downloading a vocab sheet as a PDF appears to work but the PDF file is 0 bytes. Corresponding logs:

```
2020-09-17T02:22:32.717970+00:00 app[web.1]: (node:7318) UnhandledPromiseRejectionWarning: Error: Navigation failed because browser has disconnected!
2020-09-17T02:22:32.717971+00:00 app[web.1]: at /app/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:51:147
2020-09-17T02:22:32.717972+00:00 app[web.1]: at /app/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
2020-09-17T02:22:32.717973+00:00 app[web.1]: at Array.map (<anonymous>)
2020-09-17T02:22:32.717973+00:00 app[web.1]: at Object.emit (/app/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
2020-09-17T02:22:32.717973+00:00 app[web.1]: at CDPSession.emit (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
2020-09-17T02:22:32.717974+00:00 app[web.1]: at CDPSession._onClosed (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:247:14)
2020-09-17T02:22:32.717974+00:00 app[web.1]: at Connection._onClose (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:128:21)
2020-09-17T02:22:32.717975+00:00 app[web.1]: at WebSocket.<anonymous> (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/WebSocketTransport.js:17:30)
2020-09-17T02:22:32.717975+00:00 app[web.1]: at WebSocket.onClose (/app/node_modules/ws/lib/event-target.js:129:16)
2020-09-17T02:22:32.717976+00:00 app[web.1]: at WebSocket.emit (events.js:314:20)
2020-09-17T02:22:32.717976+00:00 app[web.1]: (Use `node --trace-warnings ...` to show where the warning was created)
2020-09-17T02:22:32.718075+00:00 app[web.1]: (node:7318) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2020-09-17T02:22:32.718189+00:00 app[web.1]: (node:7318) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2020-09-17T02:22:32.742002+00:00 app[web.1]: I, [2020-09-17T02:22:32.741877 #71]  INFO -- : [126fda30-1e3d-4063-bf2e-0bd2d466fca2] method=GET path=/vocab_sheet/download_pdf format=html controller=VocabSheetsController action=download_pdf status=200 duration=1082.49 view=0.00 db=7.22 params={}
```

**Comment by joshmcarthur** [comment]
Memory looks OK

![image](https://user-images.githubusercontent.com/292020/93418536-c04ee900-f8fe-11ea-93d5-b5f948d779d5.png)

Working on replicating locally now

**Comment by joshmcarthur** [comment]
indoes are OK
Disk space is OK

**Comment by joshmcarthur** [comment]
```
~ $ ./node_modules/puppeteer/.local-chromium/linux-800071/chrome-linux/chrome --headless --no-sandbox
[0917/040707.687344:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
``

**Comment by joshmcarthur** [comment]
Attempting to clear build cache to ensure dependencies are all installed

**Comment by eoinkelly** [comment]
Tried to replicate locally but couldn't. The error is clearly from the node script.

I used `heroku ps:exec` to run the node script on the web dyno, pointing it at a html file left over from a previous conversion attempt. 

```
$ HEROKU_APP=nzsl heroku ps:exec "/app/.heroku/node/bin/node bin/render-pdf.js /app/tmp/pdf_rendering/1600368639-20b6d81ec0aefed49e26-input.html /app/tmp/eoin2.pdf"
Establishing credentials... done
Connecting to web.1 on ⬢ nzsl...
Input path: file:///app/tmp/pdf_rendering/1600368639-20b6d81ec0aefed49e26-input.html
Output path: /app/tmp/eoin2.pdf
(node:4626) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/app/node_modules/puppeteer/.local-chromium/linux-800071/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (events.js:326:22)
    at Interface.close (readline.js:424:8)
    at Socket.onend (readline.js:202:10)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1252:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4626) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4626) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```
/app/node_modules/puppeteer/.local-chromium/linux-800071/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
```

tells me the problem is with the way pupeteer is installed. https://github.com/jontewks/puppeteer-heroku-buildpack recommends purging the build cache to solve such issues so I 

1. ran `repo:purge_cache` heroku command
1. added an empty commit to `main` branch to trigger a deployment with "new" code

but this didn't fix it.

**Comment by eoinkelly** [comment]
I tried

1. Remove the https://github.com/jontewks/puppeteer-heroku-buildpack buildback
1. Purge the cache
1. Deploy again
1. Purge cache again
1. Add https://github.com/jontewks/puppeteer-heroku-buildpack back in
1. Deploy again

but I'm still getting 0 byte PDFs :-(
